### ISSUE TITLE
Table of known working cards?

### ISSUE THREAD

**Issue by nate2014jatc** [Matoking/NVIDIA-vBIOS-VFIO-Patcher#13]
Would you be willing to add a small table of the cards that you know this tool will work with?

Additionally, there is a typo in your readme;

"to he Pascal series" should be "to the Pascal series"

**Comment by Matoking** [comment]
I don't work on this script anymore, as I've switched to AMD and started using Steam's Proton instead of a VFIO + Windows setup.

I'm also hesitant to add a third-party sourced table since then I'd have to rely on that information being correct or verify it myself, which takes time. That's especially important since the script modifies VBIOS images and could cause hardware issues if an incorrect image is loaded.

**Comment by nate2014jatc** [comment]
Perfectly understandable, I gave up with the NVIDIA drivers and traded a local guy for an AMD card of similar power.
